version: "3.9"

services:
  nuxt:
    container_name: my_blog_of_nuxt
    build:
      context: .
      dockerfile: Dockerfile
    image: my_blog_of_nuxt:latest

    ports:
      - "40080:3000"        # å®¿ä¸»ç«¯å£ : å®¹å™¨ç«¯å£

    environment:
      NODE_ENV: production
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000

    # volumes:
      # ğŸ‘‰ å¦‚æœä½ æœ‰è¿è¡ŒæœŸéœ€è¦å†™å…¥çš„ç›®å½•ï¼ˆå¦‚ sqlite / uploadsï¼‰
      # - ./data:/app/data

    restart: unless-stopped
